apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mcp-kubernetes
  namespace: mcp-kubernetes
  annotations:
    tailscale.com/proxy-class: "prod"
spec:
  ingressClassName: tailscale
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mcp-kubernetes
                port:
                  number: 8000
  tls:
    - hosts:
        - mcp-kubernetes
