apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gitea-cloudflare
  namespace: gitea
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    traefik.ingress.kubernetes.io/router.middlewares: >-
      kube-system-cloudflare-https-scheme@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
    - host: git.chronobyte.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gitea-http
                port:
                  number: 3000
  tls:
    - hosts:
        - git.chronobyte.net
      secretName: gitea-cloudflare-tls
