apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backstitch-cloudflare
  namespace: backstitch
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    traefik.ingress.kubernetes.io/router.middlewares: >-
      kube-system-cloudflare-https-scheme@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
    - host: back.chronobyte.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: backstitch
                port:
                  number: 3000
  tls:
    - hosts:
        - back.chronobyte.net
      secretName: backstitch-cloudflare-tls
