apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backstitch-data
  namespace: backstitch
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
