apiVersion: v1
kind: Service
metadata:
  name: filebrowser
  namespace: jellyfin
  annotations:
    metallb.universe.tf/loadBalancerIPs: "192.168.1.241"
spec:
  type: LoadBalancer
  selector:
    app: filebrowser
  ports:
    - port: 80
      targetPort: 80
      name: http
