apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: actual-mcp-secondary-data
  namespace: actual-mcp-secondary
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
