apiVersion: v1
kind: Secret
metadata:
  name: minecraft-secrets
  namespace: minecraft
  annotations:
    kustomize.toolkit.fluxcd.io/reconcile: disabled
type: Opaque
stringData:
  RCON_PASSWORD: "REPLACE_ME"
