apiVersion: apps/v1
kind: Deployment
metadata:
  name: actual
  namespace: actual
spec:
  replicas: 1
  selector:
    matchLabels:
      app: actual
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: actual
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: actual
          image: actualbudget/actual-server:25.7.1
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 5006
          env:
            - name: ACTUAL_UPLOAD_FILE_SYNC_SIZE_LIMIT_MB
              value: "20"
            - name: ACTUAL_UPLOAD_SYNC_ENCRYPTED_FILE_SYNC_SIZE_LIMIT_MB
              value: "50"
            - name: ACTUAL_UPLOAD_FILE_SIZE_LIMIT_MB
              value: "20"
          volumeMounts:
            - name: data
              mountPath: /data
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          readinessProbe:
            httpGet:
              path: /
              port: 5006
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /
              port: 5006
            initialDelaySeconds: 30
            periodSeconds: 30
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: actual-data
