apiVersion: v1
kind: Secret
metadata:
  name: linkwarden-secrets
  namespace: linkwarden
type: Opaque
stringData:
  nextauth-secret: "REPLACE_ME_run_openssl_rand_-base64_32"
  meili-master-key: "REPLACE_ME_run_openssl_rand_-base64_32"
