apiVersion: apps/v1
kind: Deployment
metadata:
  name: pegaprox
  namespace: pegaprox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pegaprox
  template:
    metadata:
      labels:
        app: pegaprox
    spec:
      securityContext:
        fsGroup: 999
      containers:
        - name: pegaprox
          image: ghcr.io/pegaprox/pegaprox:latest
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
            - name: vnc-ws
              containerPort: 5001
              protocol: TCP
            - name: ssh-ws
              containerPort: 5002
              protocol: TCP
          env:
            - name: PEGAPROX_BEHIND_PROXY
              value: "true"
            - name: PEGAPROX_HOST
              value: "0.0.0.0"
            - name: PEGAPROX_TRUSTED_PROXIES
              value: "10.0.0.0/8,172.16.0.0/12,192.168.0.0/16"
            - name: PEGAPROX_ALLOWED_ORIGINS
              value: "https://pegaprox.daggertooth-scala.ts.net"
          volumeMounts:
            - name: config
              mountPath: /app/config
            - name: logs
              mountPath: /app/logs
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 512Mi
          readinessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 15
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 30
            periodSeconds: 30
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: pegaprox-config
        - name: logs
          persistentVolumeClaim:
            claimName: pegaprox-logs
