apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pegaprox-config
  namespace: pegaprox
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pegaprox-logs
  namespace: pegaprox
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
