apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - rbac.yaml
  - bw-secret.yaml
  - user-templates.yaml
  - config.yaml
  - deployments.yaml
  - ingress.yaml
